"""tabla alumnos con cambios

Revision ID: 679d1ff33445
Revises: 
Create Date: 2026-02-21 09:07:59.556959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '679d1ff33445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('correo',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
